[package]
name = "claw_strk_nft"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = ">=2.9.0"
openzeppelin_token = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v1.0.0" }
openzeppelin_introspection = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v1.0.0" }

[[target.starknet-contract]]
sierra = true
casm = true
